name: Tests and Linters

on: [pull_request]

env:
    PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu

jobs:
    linter:
        runs-on: ubuntu-24.04
        name: Linters
        steps:
        -   uses: actions/checkout@v4
            with:
                lfs: true
        -   name: Install uv
            uses: astral-sh/setup-uv@v5
            with:
                enable-cache: true
        -   uses: actions/setup-python@v5
            with:
                python-version-file: '.python-version'
        -   name: Install
            run: |
                git config --global url."https://${{ secrets.GIT_HUB_API_KEY }}@github.com/".insteadOf "git@github.com:"
                git config --global url."https://${{ secrets.GIT_HUB_API_KEY }}@github.com".insteadOf "https://github.com"
                uv sync --all-extras --dev
        -   name: mypy
            run: uv run mypy .
        -   name: ruff check
            run: uv run ruff check --output-format=github .
        -   name: run format
            run: uv run ruff format --check .
        -   name: check licenses
            run: uv run pip-licenses
    unit-tests:
        runs-on: ubuntu-24.04
        name: Perform unit tests
        steps:
        -   uses: actions/checkout@v4
            with:
                lfs: true
        -   name: Install uv
            uses: astral-sh/setup-uv@v5
            with:
                enable-cache: true
        -   uses: actions/setup-python@v5
            with:
                python-version-file: '.python-version'
        -   name: Install
            run: |
                git config --global url."https://${{ secrets.GIT_HUB_API_KEY }}@github.com/".insteadOf "git@github.com:"
                git config --global url."https://${{ secrets.GIT_HUB_API_KEY }}@github.com".insteadOf "https://github.com"
                uv sync --all-extras --dev
        -   name: Execute tests
            run: |
                uv run pytest .
